apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubescx-agent
  namespace: kubescx-lab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubescx-agent
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubescx-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubescx-agent
subjects:
  - kind: ServiceAccount
    name: kubescx-agent
    namespace: kubescx-lab
